const std = @import("std");

// Generated by: zig build registry
// Add Components to src/components/ and rebuild

pub const ComponentName = enum {

};

pub const ComponentTypes = [_]type {

};

pub fn getTypeByName(comptime component_name: ComponentName) type {
    const index = @intFromEnum(component_name);
    return ComponentTypes[index];
}
