const std = @import("std");

// Generated by: zig build registry
// Add Systems to src/systems/ and rebuild

pub const SystemName = enum {

};

pub const SystemTypes = [_]type {

};

pub fn getTypeByName(comptime system_name: SystemName) type {
    const index = @intFromEnum(system_name);
    return SystemTypes[index];
}
